version: "3.8" 

services:
  app:
    user: "${UID:-1000}"
    hostname: "${HOST:-arun}"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USERNAME:-arunkumar}"
        USER_ID: "${UID:-1000}"
    image: cybulde-template
    container_name: cybulde-template
    # env_file:
    #   - .envs/.app
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USERNAME:-arunkumar}/.config/gcloud
    ports:
      - 8080:8080

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    ipc: host
    init: true